using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;

namespace DATA_ASSETS
{
    public static class WorldObjects
    {
        // Properties
        public static List<Stat> STATS = new List<Stat>();
        public static List<Command> COMMANDS = new List<Command>();
        public static List<Enemy> ENEMIES = new List<Enemy>();
        public static void Load()
        {
            // Load Things
            LoadStats();
            LoadCommands();

            // Load Actors
            LoadEnemies();
        }

        static void LoadStats()
        {
            // using stats file
            using (StreamReader reader = File.OpenText(@"..\..\..\DATA_ASSETS\csv\stats.csv"))
            {
                while (!reader.EndOfStream)
                {
                    string[] tokens = reader.ReadLine().Split(',');
                    STATS.Add(new Stat(int.Parse(tokens[0]), tokens[1]));
                }
            }
        }

        static void LoadCommands()
        {
            // Add commands
            COMMANDS.Add(new View());
            COMMANDS.Add(new Input());
            COMMANDS.Add(new Quit());
            COMMANDS.Add(new Help());
        }

        static void LoadEnemies()
        {
            // Load enemy bases (without questions as they will be generated by dungeons)
        }
    }
}
